# Dataset 4: Finding Association Rules on School Supplies Dataset

*Notebook by: Allen Aboy, Franchezka Cruz, Christopher Pinpin - CSMODEL S12*

### Import Libaries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### The Dataset

For this notebook, we will be working on `Dataset 4`, whose context is ***school supplies*** bought in a shop.Each row in the dataset contains a list of items bought by a customer for a single transaction.

### Reading the Dataset

To be able to explore our dataset, our first step is to load it using pandas. We will also be converting items represented as `float` to `int`.

In [2]:
supplies_df = pd.read_csv('Dataset4.csv', header = None)
supplies_df = supplies_df.astype(pd.Int32Dtype()) # convert float to int
supplies_df

      0     1     2     3     4     5     6     7
0     3     5  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1     1     2  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
2     5     9    10    11    12    14  <NA>  <NA>
3     2     5     6    13  <NA>  <NA>  <NA>  <NA>
4     3  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
..   ..   ...   ...   ...   ...   ...   ...   ...
295   1    12  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
296   9    11    12    15    17  <NA>  <NA>  <NA>
297   1     6     7     8    10    15    18  <NA>
298  16  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
299   3     6     8     9    12    19  <NA>  <NA>

[300 rows x 8 columns]

In [3]:
supplies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       300 non-null    Int32
 1   1       257 non-null    Int32
 2   2       213 non-null    Int32
 3   3       183 non-null    Int32
 4   4       152 non-null    Int32
 5   5       115 non-null    Int32
 6   6       71 non-null     Int32
 7   7       33 non-null     Int32
dtypes: Int32(8)
memory usage: 11.8 KB

State the name of the dataset. Describe the structure of the dataset file. How many observations are there in the dataset? How many variables are there in the dataset?

THIS NEEDS TO BE SHOWN IN THE FORMAT 

BASKET 0 [3 5]

BASKET 1 [1 2]

PERO NDI KO MAGAWA NG WALANG NA T___T

In [4]:
supplies_df.values.tolist()

[[3, 5, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 2, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 9, 10, 11, 12, 14, <NA>, <NA>],
 [2, 5, 6, 13, <NA>, <NA>, <NA>, <NA>],
 [3, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 8, 9, 11, 13, <NA>, <NA>],
 [2, 9, 11, 13, 19, <NA>, <NA>, <NA>],
 [4, 5, 6, 7, 8, <NA>, <NA>, <NA>],
 [0, 8, 15, 16, <NA>, <NA>, <NA>, <NA>],
 [0, 5, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, 17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [8, 10, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 5, 9, 12, 17, 18, <NA>, <NA>],
 [6, 8, 9, 16, 17, 18, 19, <NA>],
 [7, 12, 15, 17, <NA>, <NA>, <NA>, <NA>],
 [9, 12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 3, 8, 10, 13, 16, 19, <NA>],
 [1, 8, 15, <NA>, <NA>, <NA>, <NA>, <NA>],
 [7, 9, 11, 13, 19, <NA>, <NA>, <NA>],
 [4, 10, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 9, 16, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 3, 8, 9, 11, 15, 18],
 [0, 7, 8, 9, 17, 18, 19, <NA>],
 [1, 14, 15, 17, 18, <NA>, <NA>, <NA>],
 [17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 2, 7, 8, 10, 17, 19],
 [0, 1, 5, 9, 10, 18, <NA>, <NA>],
 [16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [8, 12, 18, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 6, 9, 12, 14, 19, <NA>, <NA>],
 [0, 1, 2, 6, 10, 18, <NA>, <NA>],
 [3, 4, 5, 6, 7, 8, 11, 19],
 [9, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 3, 4, 12, 13, <NA>, <NA>, <NA>],
 [15, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [7, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 7, 9, 14, <NA>, <NA>, <NA>],
 [2, 4, 6, 12, 13, 17, <NA>, <NA>],
 [2, 4, 5, 6, 11, 13, 16, <NA>],
 [0, 1, 16, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 4, 6, 8, 14, 19, <NA>, <NA>],
 [10, 12, 18, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 8, 9, 18, 19, <NA>, <NA>],
 [0, 1, 2, 10, 12, 15, 17, <NA>],
 [1, 2, 6, 9, 12, 15, 16, <NA>],
 [2, 3, 9, 12, 13, 14, 16, <NA>],
 [1, 10, 11, 12, 18, 19, <NA>, <NA>],
 [13, 16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 9, 18, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 4, 9, 11, 18, <NA>, <NA>, <NA>],
 [8, 16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 4, 6, 9, 11, <NA>, <NA>, <NA>],
 [0, 4, 6, 8, 9, 14, 19, <NA>],
 [9, 10, 11, 13, 14, 18, 19, <NA>],
 [0, 2, 4, 7, 16, 18, <NA>, <NA>],
 [14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 4, 9, 12, 14, <NA>, <NA>, <NA>],
 [8, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [8, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, 5, 7, 11, 17, <NA>, <NA>, <NA>],
 [0, 5, 9, 15, 17, 18, 19, <NA>],
 [4, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 7, 9, 15, 16, 18, <NA>, <NA>],
 [8, 13, 17, 18, <NA>, <NA>, <NA>, <NA>],
 [0, 5, 6, 7, 8, 9, 18, <NA>],
 [9, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 2, 10, 12, 14, 15, <NA>, <NA>],
 [1, 4, 5, 6, 12, 13, 14, <NA>],
 [11, 14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 8, 13, 18, 19, <NA>, <NA>, <NA>],
 [2, 4, 6, 11, <NA>, <NA>, <NA>, <NA>],
 [9, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 7, 9, 13, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 4, 5, 8, 9, 15, 18],
 [8, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 3, 5, 9, 10, 11, 15, 16],
 [0, 6, 8, 12, 16, <NA>, <NA>, <NA>],
 [1, 5, 11, 12, 17, <NA>, <NA>, <NA>],
 [1, 2, 6, 7, 12, 14, 16, 17],
 [19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 16, 18, <NA>, <NA>, <NA>, <NA>],
 [1, 2, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 9, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 5, 7, 12, 15, 16, 18, 19],
 [2, 7, 9, 11, 13, 15, 18, 19],
 [0, 1, 2, 7, 9, 10, 14, 15],
 [2, 4, 5, 7, 13, 19, <NA>, <NA>],
 [1, 13, 15, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 3, 6, 7, 8, 11, 17],
 [6, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 5, 15, 17, <NA>, <NA>, <NA>, <NA>],
 [6, 14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [7, 18, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 4, 9, 10, 16, 18, <NA>, <NA>],
 [4, 5, 10, 11, 12, 16, <NA>, <NA>],
 [7, 8, 11, 12, 13, 18, <NA>, <NA>],
 [1, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 7, 8, 9, 13, 15, 16],
 [5, 6, 7, 8, 9, 15, 19, <NA>],
 [1, 6, 8, 19, <NA>, <NA>, <NA>, <NA>],
 [3, 8, 9, 13, 15, 17, <NA>, <NA>],
 [0, 2, 5, 11, 12, 17, 18, <NA>],
 [6, 7, 8, 16, <NA>, <NA>, <NA>, <NA>],
 [2, 4, 10, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 4, 5, 6, 14, 18, <NA>, <NA>],
 [6, 10, 15, 18, <NA>, <NA>, <NA>, <NA>],
 [1, 2, 9, 12, 14, 18, <NA>, <NA>],
 [17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 9, 19, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 2, 8, 9, 16, 18, <NA>, <NA>],
 [13, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [13, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [9, 18, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 12, 13, 14, 16, 19, <NA>],
 [3, 10, 14, 17, 19, <NA>, <NA>, <NA>],
 [0, 2, 4, 6, 15, 17, 19, <NA>],
 [1, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 2, 4, 6, 12, 16, 19, <NA>],
 [9, 14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 2, 7, 17, <NA>, <NA>, <NA>, <NA>],
 [6, 7, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 3, 17, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 5, 10, 11, 13, 19, <NA>, <NA>],
 [12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [8, 9, 11, 15, 16, 17, <NA>, <NA>],
 [11, 17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, 5, 10, 11, 16, 17, 18, 19],
 [2, 8, 17, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 6, 9, 11, 12, 15, 17],
 [6, 14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [7, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 7, 9, 10, 11, 12, 17, 19],
 [1, 3, 4, 5, 9, 16, 19, <NA>],
 [2, 4, 5, 9, 11, 13, 14, <NA>],
 [1, 3, 4, 15, 18, 19, <NA>, <NA>],
 [2, 3, 18, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 3, 8, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 6, 8, 10, 11, <NA>, <NA>],
 [8, 13, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 5, 10, 12, <NA>, <NA>, <NA>, <NA>],
 [4, 10, 11, 16, <NA>, <NA>, <NA>, <NA>],
 [0, 3, 12, 13, <NA>, <NA>, <NA>, <NA>],
 [3, 4, 5, 13, 16, <NA>, <NA>, <NA>],
 [4, 6, 14, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 9, 11, 14, 17, 18, <NA>, <NA>],
 [2, 9, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [6, 10, 12, 14, 15, 19, <NA>, <NA>],
 [2, 3, 13, 15, 16, 18, <NA>, <NA>],
 [2, 3, 5, 8, 9, 15, 17, <NA>],
 [2, 4, 15, 16, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 4, 5, 15, 17, 18, <NA>],
 [1, 3, 8, 10, 11, 12, 16, <NA>],
 [1, 11, 12, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 5, 6, 11, 12, <NA>, <NA>],
 [0, 1, 2, 3, 5, 7, 8, 9],
 [1, 3, 6, 11, 12, 14, 18, 19],
 [0, 4, 7, 14, 15, <NA>, <NA>, <NA>],
 [17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, 7, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 3, 13, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 4, 7, 9, 11, 14, 18, <NA>],
 [1, 4, 8, 11, 12, 13, 17, 18],
 [2, 11, 15, 16, <NA>, <NA>, <NA>, <NA>],
 [7, 12, 13, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 9, 13, 16, 17, <NA>, <NA>, <NA>],
 [0, 2, 3, 6, 12, 14, <NA>, <NA>],
 [0, 2, 4, 5, 9, 13, 18, 19],
 [1, 3, 7, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 5, 8, 9, 11, 15, 17, 19],
 [13, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 6, 14, 15, 16, <NA>, <NA>, <NA>],
 [4, 5, 12, 16, 18, <NA>, <NA>, <NA>],
 [7, 13, 14, 17, <NA>, <NA>, <NA>, <NA>],
 [8, 11, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 4, 8, 11, 12, 15, 17],
 [0, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [10, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 4, 6, 9, 11, 13, 15, 16],
 [12, 18, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 7, 9, 11, 12, 13, 18, <NA>],
 [4, 14, 17, 18, <NA>, <NA>, <NA>, <NA>],
 [3, 6, 8, 9, 13, 14, 16, 17],
 [1, 5, 8, 14, 15, <NA>, <NA>, <NA>],
 [0, 4, 5, 8, 9, 12, 13, 18],
 [0, 1, 2, 14, 18, <NA>, <NA>, <NA>],
 [0, 1, 4, 9, 12, 13, 14, <NA>],
 [0, 5, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 10, 15, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 6, 13, 17, 18, <NA>, <NA>, <NA>],
 [1, 2, 4, 10, 17, <NA>, <NA>, <NA>],
 [0, 1, 3, 5, 9, 13, 19, <NA>],
 [1, 6, 12, 17, <NA>, <NA>, <NA>, <NA>],
 [0, 9, 11, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 5, 6, 10, 12, 13, 14, 17],
 [1, 2, 3, 4, 7, 8, 15, <NA>],
 [5, 8, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 8, 14, <NA>, <NA>, <NA>, <NA>, <NA>],
 [11, 14, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 6, 7, 10, 14, 15, 19, <NA>],
 [3, 4, 7, 15, 16, <NA>, <NA>, <NA>],
 [1, 4, 8, 10, 18, <NA>, <NA>, <NA>],
 [0, 3, 8, 11, 17, <NA>, <NA>, <NA>],
 [16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 4, 5, 7, 16, <NA>, <NA>],
 [3, 12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 13, 17, 18, 19, <NA>, <NA>, <NA>],
 [0, 1, 2, 3, 8, 10, 12, 18],
 [1, 3, 4, 15, 16, <NA>, <NA>, <NA>],
 [0, 1, 2, 7, 11, 14, 18, <NA>],
 [19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 12, 13, 14, 15, 18, 19, <NA>],
 [1, 6, 9, 10, 17, 18, <NA>, <NA>],
 [3, 7, 15, 18, <NA>, <NA>, <NA>, <NA>],
 [1, 4, 9, 11, 12, 15, 18, 19],
 [0, 4, 8, 11, 13, 14, <NA>, <NA>],
 [0, 1, 5, 7, 11, 12, 13, 14],
 [0, 5, 7, 8, 10, 14, 17, <NA>],
 [1, 2, 5, 10, 13, 14, 15, 18],
 [5, 7, 9, 18, 19, <NA>, <NA>, <NA>],
 [8, 11, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 6, 8, 9, 11, 13, 17],
 [7, 11, 19, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 6, 8, 11, 15, 16, 17],
 [0, 8, 12, 17, <NA>, <NA>, <NA>, <NA>],
 [0, 6, 10, 12, 18, 19, <NA>, <NA>],
 [2, 11, 15, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 2, 5, 10, 17, 18, <NA>],
 [6, 8, 12, 15, 16, <NA>, <NA>, <NA>],
 [12, 14, 16, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 6, 7, 8, 14, <NA>, <NA>],
 [1, 2, 5, 10, 15, <NA>, <NA>, <NA>],
 [11, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [6, 7, 11, 13, 16, 19, <NA>, <NA>],
 [0, 2, 9, 10, 13, 15, 19, <NA>],
 [7, 8, 9, 13, 14, 15, 16, 17],
 [2, 11, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 12, 19, <NA>, <NA>, <NA>, <NA>],
 [8, 10, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 5, 12, 14, 16, 18, <NA>, <NA>],
 [3, 7, 8, 11, 14, 15, 18, 19],
 [0, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [5, 6, 16, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 5, 14, 17, 18, 19, <NA>, <NA>],
 [3, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, 5, 8, 9, 10, <NA>, <NA>, <NA>],
 [4, 16, 17, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 7, 10, 11, 12, 17, <NA>, <NA>],
 [1, 6, 8, 10, 15, 17, <NA>, <NA>],
 [8, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 5, 6, 9, 11, 15, 18],
 [0, 4, 9, 11, 12, 17, <NA>, <NA>],
 [1, 3, 4, 11, <NA>, <NA>, <NA>, <NA>],
 [1, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 11, 13, <NA>, <NA>, <NA>, <NA>, <NA>],
 [6, 8, 13, 16, 18, 19, <NA>, <NA>],
 [4, 10, 12, 16, <NA>, <NA>, <NA>, <NA>],
 [3, 7, 8, 13, 15, 19, <NA>, <NA>],
 [4, 11, 17, 19, <NA>, <NA>, <NA>, <NA>],
 [0, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [9, 11, 12, 15, <NA>, <NA>, <NA>, <NA>],
 [13, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 3, 9, 15, 19, <NA>, <NA>, <NA>],
 [5, 15, 18, <NA>, <NA>, <NA>, <NA>, <NA>],
 [12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 12, 16, 19, <NA>, <NA>, <NA>, <NA>],
 [10, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [4, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 5, 6, 15, 18, <NA>, <NA>, <NA>],
 [0, 5, 6, 7, 15, 16, 17, <NA>],
 [8, 9, 17, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 2, 3, 4, 5, 7, 17, <NA>],
 [0, 5, 6, 14, <NA>, <NA>, <NA>, <NA>],
 [11, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [13, 14, 17, 18, <NA>, <NA>, <NA>, <NA>],
 [1, 7, 9, 10, 11, 12, 16, <NA>],
 [3, 10, 15, 18, 19, <NA>, <NA>, <NA>],
 [4, 19, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [2, 16, 19, <NA>, <NA>, <NA>, <NA>, <NA>],
 [13, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 8, 9, 15, 19, <NA>, <NA>, <NA>],
 [1, 3, 4, 9, <NA>, <NA>, <NA>, <NA>],
 [1, 9, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [0, 1, 4, 5, 14, 17, 19, <NA>],
 [0, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [17, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [1, 12, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [9, 11, 12, 15, 17, <NA>, <NA>, <NA>],
 [1, 6, 7, 8, 10, 15, 18, <NA>],
 [16, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>],
 [3, 6, 8, 9, 12, 19, <NA>, <NA>]]

In [5]:
values = supplies_df.values.ravel()
values = [value for value in pd.unique(values) if not pd.isnull(value)]

value_dict = {}
for i, value in enumerate(values):
    value_dict[value] = i
    
temp_df = supplies_df.stack().map(value_dict).unstack()

carts = []
for i in range(temp_df.shape[0]):
    cart = np.sort([int(x) for x in temp_df.iloc[i].values.tolist() if str(x) != 'nan'])
    carts.append(cart)
    
supplies_df = pd.DataFrame([[0 for _ in range(20)] for _ in range(300)], columns=values)

for i, cart in enumerate(carts):
    supplies_df.iloc[i, cart] = 1

    
supplies_df = supplies_df.reindex(sorted(supplies_df.columns), axis=1)

In [6]:
supplies_df.columns = ['Bond Paper','Index Card','Intermediate Pad Paper',
                        'Construction Paper','Pencil','Sharpener',
                        'Eraser','Marker','Yellow Pad',
                        'Crayon','Whiteboard','Ruler',
                        'Graph Paper','Protractor','Paint Brush',
                        'Poster Paint','Acrylic Paint','Watercolor',
                        'Canvas','Notebook']
supplies_df

,Bond Paper,Index Card,Intermediate Pad Paper,Construction Paper,Pencil,Sharpener,Eraser,Marker,Yellow Pad,Crayon,Whiteboard,Ruler,Graph Paper,Protractor,Paint Brush,Poster Paint,Acrylic Paint,Watercolor,Canvas,Notebook
0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,1,1,1,1,0,1,0,0,0,0,0
3,0,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
296,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,1,0,0
297,0,1,0,0,0,0,1,1,1,0,1,0,0,0,0,1,0,0,1,0
298,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
299,0,0,0,1,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,1

# DI KO ALAM IF NECESSARY PA TO PERO FEEL KO NDI NA KASI NUMBERS NA SYA MINAMAP LANG TO INTO DICTIONARY

In [7]:
baskets = []
for i in range(temp_df.shape[0]):
    basket = np.sort([int(x) for x in temp_df.iloc[i].values.tolist() if str(x) != 'nan'])
    baskets.append(basket)

In [8]:
for i, basket in enumerate(baskets):
    print('Basket', i, basket)

Basket 0 [0 1]
Basket 1 [2 3]
Basket 2 [1 4 5 6 7 8]
Basket 3 [ 1  3  9 10]
Basket 4 [0]
Basket 5 [ 3  4  6 10 11 12]
Basket 6 [ 3  4  6 10 13]
Basket 7 [ 1  9 12 14 15]
Basket 8 [11 12 16 17]
Basket 9 [ 1 11]
Basket 10 [14 18]
Basket 11 [ 5 12]
Basket 12 [ 1  3  4  7 18 19]
Basket 13 [ 4  9 12 13 17 18 19]
Basket 14 [ 7 15 16 18]
Basket 15 [4 7]
Basket 16 [ 0  5 10 11 12 13 17]
Basket 17 [ 2 12 16]
Basket 18 [ 4  6 10 13 15]
Basket 19 [ 5 14]
Basket 20 [ 0  4 17]
Basket 21 [ 0  2  4  6 11 12 16 19]
Basket 22 [ 4 11 12 13 15 18 19]
Basket 23 [ 2  8 16 18 19]
Basket 24 [18]
Basket 25 [ 2  3  5 11 12 13 15 18]
Basket 26 [ 1  2  4  5 11 19]
Basket 27 [17]
Basket 28 [ 7 12 19]
Basket 29 [ 3  4  7  8  9 13]
Basket 30 [ 2  3  5  9 11 19]
Basket 31 [ 0  1  6  9 12 13 14 15]
Basket 32 [4]
Basket 33 [ 0  3  7 10 14]
Basket 34 [16]
Basket 35 [15]
Basket 36 [ 3  4  8 11 15]
Basket 37 [ 3  7  9 10 14 18]
Basket 38 [ 1  3  6  9 10 14 17]
Basket 39 [ 2 11 17]
Basket 40 [ 2  8  9 12 13 14]
Basket 41 [ 5  7 19]
Basket 42 [ 3  4 11 12 13 19]
Basket 43 [ 2  3  5  7 11 16 18]
Basket 44 [ 2  3  4  7  9 16 17]
Basket 45 [ 0  3  4  7  8 10 17]
Basket 46 [ 2  5  6  7 13 19]
Basket 47 [10 17]
Basket 48 [ 4 11 19]
Basket 49 [ 4  6 11 14 19]
Basket 50 [12 17]
Basket 51 [ 0  4  6  9 14]
Basket 52 [ 4  8  9 11 12 13 14]
Basket 53 [ 4  5  6  8 10 13 19]
Basket 54 [ 3 11 14 15 17 19]
Basket 55 [8]
Basket 56 [ 3  4  7  8 14]
Basket 57 [12]
Basket 58 [12]
Basket 59 [ 1  6 14 15 18]
Basket 60 [ 1  4 11 13 16 18 19]
Basket 61 [13 14]
Basket 62 [2]
Basket 63 [ 4 11 15 16 17 19]
Basket 64 [10 12 18 19]
Basket 65 [ 1  4  9 11 12 15 19]
Basket 66 [ 4 13]
Basket 67 [ 2  3  5  7  8 16]
Basket 68 [ 1  2  7  8  9 10 14]
Basket 69 [6 8]
Basket 70 [ 2 10 12 13 19]
Basket 71 [ 3  6  9 14]
Basket 72 [4]
Basket 73 [ 2  4 10 15]
Basket 74 [ 0  1  2  4 12 14 16 19]
Basket 75 [12]
Basket 76 [ 0  1  3  4  5  6 16 17]
Basket 77 [ 7  9 11 12 17]
Basket 78 [ 1  2  6  7 18]
Basket 79 [ 2  3  7  8  9 15 17 18]
Basket 80 [13]
Basket 81 [ 2 11 17 19]
Basket 82 [2 3]
Basket 83 [0 4]
Basket 84 [ 1  7 11 13 15 16 17 19]
Basket 85 [ 3  4  6 10 13 15 16 19]
Basket 86 [ 2  3  4  5  8 11 15 16]
Basket 87 [ 1  3 10 13 14 15]
Basket 88 [ 2 10 16]
Basket 89 [ 0  3  6  9 11 12 15 18]
Basket 90 [9]
Basket 91 [7]
Basket 92 [ 1  2 16 18]
Basket 93 [8 9]
Basket 94 [15 19]
Basket 95 [ 4  5 11 14 17 19]
Basket 96 [ 1  5  6  7 14 17]
Basket 97 [ 6  7 10 12 15 19]
Basket 98 [2]
Basket 99 [13]
Basket 100 [ 2  4 10 11 12 15 16 17]
Basket 101 [ 1  4  9 12 13 15 16]
Basket 102 [ 2  9 12 13]
Basket 103 [ 0  4 10 12 16 18]
Basket 104 [ 1  3  6  7 11 18 19]
Basket 105 [ 9 12 15 17]
Basket 106 [ 3  5 14]
Basket 107 [ 1  8  9 11 14 19]
Basket 108 [ 5  9 16 19]
Basket 109 [ 2  3  4  7  8 19]
Basket 110 [18]
Basket 111 [ 4 11 13]
Basket 112 [ 2  3  4 12 17 19]
Basket 113 [10]
Basket 114 [ 1 13]
Basket 115 [10 13]
Basket 116 [ 4 19]
Basket 117 [ 2  7  8 10 11 13 17]
Basket 118 [ 0  5  8 13 18]
Basket 119 [ 3  9 11 13 14 16 18]
Basket 120 [2]
Basket 121 [ 2  3  7  9 13 14 17]
Basket 122 [4 8]
Basket 123 [ 2  3 15 18]
Basket 124 [ 9 15]
Basket 125 [ 0 11 18]
Basket 126 [ 1  5  6 10 11 13]
Basket 127 [7]
Basket 128 [ 4  6 12 16 17 18]
Basket 129 [ 6 18]
Basket 130 [ 1  5  6 13 14 17 18 19]
Basket 131 [ 3 12 18]
Basket 132 [ 0  2  4  6  7  9 16 18]
Basket 133 [8 9]
Basket 134 [15]
Basket 135 [ 0  4  5  6  7 13 15 18]
Basket 136 [ 0  1  2  4 13 14 17]
Basket 137 [ 1  3  4  6  8 10 14]
Basket 138 [ 0  2 13 14 16 19]
Basket 139 [ 0  3 19]
Basket 140 [ 0  3 12]
Basket 141 [ 0  2  5  6  9 12]
Basket 142 [10 12]
Basket 143 [0 1 5 7]
Basket 144 [ 5  6 14 17]
Basket 145 [ 0  7 10 11]
Basket 146 [ 0  1 10 14 17]
Basket 147 [ 8  9 14]
Basket 148 [ 3  4  6  8 18 19]
Basket 149 [3 4]
Basket 150 [ 5  7  8  9 13 16]
Basket 151 [ 0  3 10 16 17 19]
Basket 152 [ 0  1  3  4 12 16 18]
Basket 153 [ 3 14 16 17]
Basket 154 [ 1  2 11 14 16 18 19]
Basket 155 [ 0  2  5  6  7 12 17]
Basket 156 [2 6 7]
Basket 157 [0 1 2 6 7 9]
Basket 158 [ 0  1  2  3  4 11 12 15]
Basket 159 [ 0  2  6  7  8  9 13 19]
Basket 160 [ 8 11 14 15 16]
Basket 161 [18]
Basket 162 [14 15]
Basket 163 [ 0 10 11]
Basket 164 [ 4  6  8 11 14 15 19]
Basket 165 [ 2  6  7 10 12 14 18 19]
Basket 166 [ 3  6 16 17]
Basket 167 [ 7 10 15]
Basket 168 [ 1  4 10 17 18]
Basket 169 [ 0  3  7  8  9 11]
Basket 170 [ 1  3  4 10 11 13 14 19]
Basket 171 [ 0  2 15]
Basket 172 [ 1  3  4  6 12 13 16 18]
Basket 173 [10 13]
Basket 174 [ 0  8  9 16 17]
Basket 175 [ 1  7 14 17 19]
Basket 176 [ 8 10 15 18]
Basket 177 [ 6 12]
Basket 178 [ 3  6  7 11 12 14 16 18]
Basket 179 [11]
Basket 180 [5]
Basket 181 [ 3  4  6  9 10 14 16 17]
Basket 182 [ 7 19]
Basket 183 [ 0  4  6  7 10 15 19]
Basket 184 [ 8 14 18 19]
Basket 185 [ 0  4  8  9 10 12 17 18]
Basket 186 [ 1  2  8 12 16]
Basket 187 [ 1  4  7 10 11 12 14 19]
Basket 188 [ 2  3  8 11 19]
Basket 189 [ 2  4  7  8 10 11 14]
Basket 190 [ 1 11]
Basket 191 [18]
Basket 192 [ 1  5 16]
Basket 193 [ 3  9 10 18 19]
Basket 194 [ 2  3  5 14 18]
Basket 195 [ 0  1  2  4 10 11 13]
Basket 196 [ 2  7  9 18]
Basket 197 [ 4  6 11]
Basket 198 [ 1  5  7  8  9 10 11 18]
Basket 199 [ 0  2  3 12 14 15 16]
Basket 200 [ 1 12]
Basket 201 [ 3  8 12]
Basket 202 [6 8]
Basket 203 [ 2  5  8  9 13 15 16]
Basket 204 [ 0 14 15 16 17]
Basket 205 [ 2  5 12 14 19]
Basket 206 [ 0  6 11 12 18]
Basket 207 [17]
Basket 208 [13]
Basket 209 [ 1  3 11 14 15 17]
Basket 210 [0 7]
Basket 211 [1]
Basket 212 [ 3 10 13 18 19]
Basket 213 [ 0  2  3  5  7 11 12 19]
Basket 214 [ 0  2 14 16 17]
Basket 215 [ 2  3  6  8 11 15 19]
Basket 216 [13]
Basket 217 [ 1  7  8 10 13 16 19]
Basket 218 [ 2  4  5  9 18 19]
Basket 219 [ 0 15 16 19]
Basket 220 [ 2  4  6  7 13 14 16 19]
Basket 221 [ 6  8 10 11 12 14]
Basket 222 [ 1  2  6  7  8 10 11 15]
Basket 223 [ 1  5  8 11 12 15 18]
Basket 224 [ 1  2  3  5  8 10 16 19]
Basket 225 [ 1  4 13 15 19]
Basket 226 [ 6 12]
Basket 227 [ 2  4  6  9 10 11 12 18]
Basket 228 [ 6 13 15]
Basket 229 [ 0  2  6  9 12 16 17 18]
Basket 230 [ 7 11 12 18]
Basket 231 [ 5  7  9 11 13 19]
Basket 232 [ 3  6 16]
Basket 233 [ 1  2  3  5 11 18 19]
Basket 234 [ 7  9 12 16 17]
Basket 235 [ 7  8 17]
Basket 236 [ 2  8  9 11 12 15]
Basket 237 [ 1  2  3  5 16]
Basket 238 [6]
Basket 239 [ 6  9 10 13 15 17]
Basket 240 [ 3  4  5 10 11 13 16]
Basket 241 [ 4  8 10 12 15 16 17 18]
Basket 242 [3 6]
Basket 243 [ 2  7 11 13]
Basket 244 [ 5 12]
Basket 245 [ 1  3  7  8 17 19]
Basket 246 [ 0  6  8 12 13 15 16 19]
Basket 247 [11]
Basket 248 [ 1  9 17]
Basket 249 [ 1  2  8 13 18 19]
Basket 250 [ 0 13]
Basket 251 [ 1  4  5 12 14]
Basket 252 [14 17 18]
Basket 253 [ 2  5  6  7 15 18]
Basket 254 [ 2  5  9 12 16 18]
Basket 255 [12 13]
Basket 256 [ 1  3  4  6  9 11 16 19]
Basket 257 [ 4  6  7 11 14 18]
Basket 258 [ 0  2  6 14]
Basket 259 [2]
Basket 260 [ 3  6 10]
Basket 261 [ 9 10 12 13 17 19]
Basket 262 [ 5  7 14 17]
Basket 263 [ 0 10 12 13 15 16]
Basket 264 [ 6 13 14 18]
Basket 265 [11]
Basket 266 [17]
Basket 267 [ 4  6  7 16]
Basket 268 [10 13]
Basket 269 [ 0  2  4 13 16]
Basket 270 [ 1 16 19]
Basket 271 [7]
Basket 272 [ 3  7 13 17]
Basket 273 [ 5 13]
Basket 274 [11 13]
Basket 275 [13]
Basket 276 [14]
Basket 277 [ 1  3  9 16 19]
Basket 278 [ 1  9 11 15 16 17 18]
Basket 279 [ 4 12 18]
Basket 280 [ 0  1  3 11 14 15 18]
Basket 281 [ 1  8  9 11]
Basket 282 [6]
Basket 283 [ 8 10 18 19]
Basket 284 [ 2  4  5  6  7 15 17]
Basket 285 [ 0  5 13 16 19]
Basket 286 [13 14]
Basket 287 [ 3 13 17]
Basket 288 [10]
Basket 289 [ 4 11 12 13 16]
Basket 290 [ 0  2  4 14]
Basket 291 [2 4]
Basket 292 [ 1  2  8 11 13 14 18]
Basket 293 [11]
Basket 294 [18]
Basket 295 [2 7]
Basket 296 [ 4  6  7 16 18]
Basket 297 [ 2  5  9 12 15 16 19]
Basket 298 [17]
Basket 299 [ 0  4  7  9 12 13]

In [9]:
values = supplies_df.values.ravel()
values = [value for value in pd.unique(values) if not pd.isnull(value)]

value_dict = {}
for i, value in enumerate(values):
    value_dict[value] = i
    
print(value_dict)
print("Unique values: " + str(len(values)))

{0: 0, 1: 1}
Unique values: 2

In [10]:
# mali thsis 

baskets = []

for i in range(supplies_df.shape[0]): 
    basket = [int(x) for x in supplies_df.values.tolist() if str(x) != '<NA>']

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [11]:
supplies_df.describe()

,Bond Paper,Index Card,Intermediate Pad Paper,Construction Paper,Pencil,Sharpener,Eraser,Marker,Yellow Pad,Crayon,Whiteboard,Ruler,Graph Paper,Protractor,Paint Brush,Poster Paint,Acrylic Paint,Watercolor,Canvas,Notebook
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,0.253333,0.266667,0.240000,0.186667,0.213333,0.216667,0.196667,0.186667,0.243333,0.270000,0.166667,0.230000,0.230000,0.200000,0.186667,0.220000,0.196667,0.226667,0.240000,0.243333
std,0.435647,0.442956,0.427797,0.390295,0.410346,0.412662,0.398142,0.390295,0.429812,0.444701,0.373301,0.421536,0.421536,0.400668,0.390295,0.414938,0.398142,0.419375,0.427797,0.429812
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Exploratory Data Analysis

### What are the Top 5 most common items bought in the bookstore?

In [13]:
suppliesCount = []
for i in supplies_df.columns:
    supplyBought = supplies_df[i].value_counts()
    suppliesCount.append([i,supplyBought[1]])
    
suppliesCount.sort(key=lambda x: x[1], reverse=True)


supplies_df[supplies_df == 1].count() #Put into another variable


#for i in range(len(gamesCount)):
    #print(gamesCount[i][0],":",gamesCount[i][1])
    
    
countSupplies = [] 
for i in range(len(suppliesCount)):
    countSupplies.append(suppliesCount[i][1])

        
nameSupplies = [] 
for i in range(len(suppliesCount)):
    nameSupplies.append(suppliesCount[i][0])
    

eda1_df      = pd.DataFrame(data = countSupplies);
eda1_df.index = nameSupplies;

eda1_df.rename(columns={ eda1_df.columns[0]: "Supply Count" }, inplace = True)
eda1_df

                        Supply Count
Crayon                            81
Index Card                        80
Bond Paper                        76
Yellow Pad                        73
Notebook                          73
Intermediate Pad Paper            72
Canvas                            72
Ruler                             69
Graph Paper                       69
Watercolor                        68
Poster Paint                      66
Sharpener                         65
Pencil                            64
Protractor                        60
Eraser                            59
Acrylic Paint                     59
Construction Paper                56
Marker                            56
Paint Brush                       56
Whiteboard                        50